-- ============================================
-- TEST DATA - Marriage Game
-- ============================================
USE marriage_game;

-- Category IDs from 02_default_data.sql:
-- 1=Generale, 2=Storia, 3=Sport, 4=Scienze, 5=Geografia, 6=Film, 7=Arte, 8=Musica, 9=Cucina
-- Insert sample questions (45 questions, 5 per category, mixed types)
INSERT INTO
    questions (
        question_type,
        question,
        option1,
        option2,
        option3,
        option4,
        category_id,
        correct_answer,
        timer
    )
VALUES
    -- ── Sport (3) ─────────────────────────────────────────────────────
    (
        'clickfirst',
        'Quanti mondiali ha vinto l''Italia?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi ha vinto il primo mondiale di calcio?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è stato il primo club italiano di calcio?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è l''unico torneo del Grande Slam che si gioca sull''erba?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale tennista ha vinto più Slam?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale paese è nato il ping-pong?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale paese è stato inventato il gioco degli scacchi?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale campione di boxe è rimasto imbattuto nel corso della sua carriera?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Dove sono stati ospitati i primi Giochi Olimpici?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quando si sono tenuti i primi Giochi Olimpici nell''era moderna?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale atleta ha vinto più medaglie olimpiche nella storia delle olimpiadi?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Dove si svolgeranno le olimpiadi nel 2028?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è la nazione che ha vinto più medaglie alle Olimpiadi invernali?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale sport si disputa la Ryder Cup?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quanti mondiali ha vinto Valentino Rossi?',
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        10
    ),
    -- ── Musica (8) ────────────────────────────────────────────────────
    (
        'clickfirst',
        'Chi cantava "Su di Noi"?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Di quale gruppo è la canzone "Let It Be"?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Da quale città provengono i Beatles?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi è considerato il re del Rock?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi cantava la canzone "Cacao Meravigliao"?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è l''album più venduto della storia?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Che canzone hanno ballato Jay - Z e Beyoncé come primo ballo al loro matrimonio?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il chitarrista più influente di tutti i tempi secondo la rivista Rolling Stone?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il singolo più venduto in Italia nel XXI secolo?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è la prima canzone cantata nello spazio?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In che anno è morto Freddy Mercury?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale cantante italiana è conosciuta come la "Tigre di Cremona"?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi ha vinto più Grammy Award? (premio musicale più prestigioso al mondo)',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale cantante ha vinto più volte il Festival di Sanremo?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi è l''artista italiano con più album venduti nella storia?',
        NULL,
        NULL,
        NULL,
        NULL,
        8,
        NULL,
        10
    ),
    -- ── Geografia (5) ─────────────────────────────────────────────────
    (
        'clickfirst',
        'Quante strisce ci sono sulla bandiera americana?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è lo stato più antico del Mondo ancora esistente?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il fiore nazionale del Giappone?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è l''isola più grande del Mondo?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è lo stato più piccolo del Mondo?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale paese ha come animale nazionale l''unicorno come simbolo?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è la montagna più alta del Mondo?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il fiume più lungo d''Italia?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il fiume più lungo d''Europa?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il deserto più grande del mondo?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quanti sono i continenti?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quali paesi si trova l''Everest?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il nome gergale di New York, usato dai suoi abitanti?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quante e quali lingue ufficiali ci sono in Svizzera?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è la lingua più parlata al mondo da madrelingua?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiamano gli abitanti del Madagascar?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    -- ── Geografia - Abitanti (5) ──────────────────────────────────────
    (
        'clickfirst',
        'Come si chiamano gli abitanti di La Spezia (Liguria)?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiamano gli abitanti di Ancona (Marche)?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiamano gli abitanti di Chieti (Abruzzo)?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiamano gli abitanti di Domodossola (Piemonte)?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiamano gli abitanti di Ivrea (Piemonte)?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiamano gli abitanti di Caltanissetta (Sicilia)?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiamano gli abitanti di Frosinone (Lazio)?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiamano gli abitanti di Gubbio (Umbria)?',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        NULL,
        10
    ),
    -- ── Cucina (9) ────────────────────────────────────────────────────
    (
        'clickfirst',
        'Che cosa sono i Culurgiones?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale regione italiana è originaria la pasta Ravioli?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale regione italiana è originaria la pasta Bigolo?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale regione italiana è originaria la pasta Spaghetti alla Chitarra?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale regione italiana è originaria la pasta Cavatelli?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale regione italiana è originaria la pasta Fregola?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Che cosa è la piscialandrea?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Da quale paese proviene la salsa barbecue?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale frutto si trova nel dolce tedesco chiamato Foresta Nera?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il principale ingrediente del guacamole?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Dove è stato inventato il gelato?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è la bevanda più consumata al mondo dopo l''acqua?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale paese è nato il croissant?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    -- ── Film (6) ──────────────────────────────────────────────────────
    (
        'clickfirst',
        'Chi era il protagonista del film "Tempi Moderni"?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi era il protagonista del film "Il Marchese del Grillo"?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi era il protagonista del film "Titanic"?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi ha diretto il film Pulp Fiction?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale film ha vinto più Oscar nella storia del cinema e quanti?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il nome della caffetteria nella sitcom Friends?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale serie compare il personaggio "Spadino"?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale serie compare il personaggio Sheldon Cooper?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale personaggio Harrison Ford interpretava in Guerre Stellari?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Perché il premio Oscar si chiama così?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è stato il primo lungometraggio della Disney?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il primo lungometraggio della Pixar?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiama il protagonista de "Il Gobbo di Notre-Dame"?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il nome del cane della famiglia Simpson?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il soprannome del protagonista de "La Spada nella Roccia"?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il passatempo preferito di Belle?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiama il protagonista di "Cars"?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale film Disney si canta la canzone "Let It Go"?',
        NULL,
        NULL,
        NULL,
        NULL,
        6,
        NULL,
        10
    ),
    -- ── Scienze / Tecnologie (4) ──────────────────────────────────────
    (
        'clickfirst',
        'Qual è la più antica casa automobilistica al mondo?',
        NULL,
        NULL,
        NULL,
        NULL,
        4,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale anno è avvenuto il primo sbarco sulla Luna?',
        NULL,
        NULL,
        NULL,
        NULL,
        4,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è stato il primo SMS della storia?',
        NULL,
        NULL,
        NULL,
        NULL,
        4,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In che anno è stato inventato il walkman?',
        NULL,
        NULL,
        NULL,
        NULL,
        4,
        NULL,
        10
    ),
    -- ── Storia (2) ────────────────────────────────────────────────────
    (
        'clickfirst',
        'Chi era il generale della disfatta di Caporetto?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In che anno è entrata in vigore la Costituzione Italiana?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quando è nata la Repubblica Italiana?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è stato il primo presidente della Repubblica Italiana?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale anno è iniziata la Prima guerra mondiale?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi è stato l''ultimo marito di Cleopatra?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è l''anno della caduta del muro di Berlino?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In che anno avvenne la Rivoluzione francese?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In che anno Cristoforo Colombo scoprì l''America?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Sul biglietto da visita di Al Capone cosa indicava come sua occupazione?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è l''università più antica del Mondo Occidentale?',
        NULL,
        NULL,
        NULL,
        NULL,
        2,
        NULL,
        10
    ),
    -- ── Arte (7) ──────────────────────────────────────────────────────
    (
        'clickfirst',
        'Chi ha dipinto "La Notte Stellata"?',
        NULL,
        NULL,
        NULL,
        NULL,
        7,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi ha dipinto "Le 3 Grazie"?',
        NULL,
        NULL,
        NULL,
        NULL,
        7,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi ha dipinto "L''Ultima Cena"?',
        NULL,
        NULL,
        NULL,
        NULL,
        7,
        NULL,
        10
    ),
    (
        'clickfirst',
        'In quale città si trova "L''Ultima Cena"?',
        NULL,
        NULL,
        NULL,
        NULL,
        7,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale artista ha dipinto il soffitto della Cappella Sistina a Roma?',
        NULL,
        NULL,
        NULL,
        NULL,
        7,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiama il museo di arte moderna di New York?',
        NULL,
        NULL,
        NULL,
        NULL,
        7,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale artista è famoso per le lattine di zuppa Campbell?',
        NULL,
        NULL,
        NULL,
        NULL,
        7,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Dove si trova la Cappella Sistina?',
        NULL,
        NULL,
        NULL,
        NULL,
        7,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi fu definito "Il Divino"?',
        NULL,
        NULL,
        NULL,
        NULL,
        7,
        NULL,
        10
    ),
    -- ── Cucina / Bevande (9) ──────────────────────────────────────────
    (
        'clickfirst',
        'Come si prepara il cocktail Spritz?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale cocktail deve il suo nome ad un conte famoso?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Differenza tra Negroni e Negroni Sbagliato?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Da chi prende il nome il cocktail Bloody Mary?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il principale ingrediente della birra?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Dove è stato creato il cocktail Mojito?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Da quale pianta si ottiene il Rum?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il nome del distillato ottenuto dalla fermentazione di patate?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'A quale stato è comunemente associato il whiskey Jack Daniel''s?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale bevanda è conosciuta come la Fata Verde?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il famoso drink bevuto da James Bond con la iconica frase?',
        NULL,
        NULL,
        NULL,
        NULL,
        9,
        NULL,
        10
    ),
    -- ── Generale / Animali (1) ────────────────────────────────────────
    (
        'clickfirst',
        'A che specie appartiene l''Opossum?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è l''uccello che può nuotare ma non volare?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è l''unico mammifero a non poter saltare?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è l''animale nazionale dell''Italia?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiama la pecora femmina?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è l''uccello che può volare all''indietro?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è l''unico mammifero a saper volare?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    -- ── Generale / Moda (1) ───────────────────────────────────────────
    (
        'clickfirst',
        'Chi era lo stilista del famoso vestito indossato da Jennifer Lopez al Grammy del 2000?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Che colore ha dato il nome lo stilista Valentino, detto anche l''imperatore?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi era lo stilista che vestiva le SS Tedesche?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è stato il brand ad aver venduto di più durante la pandemia?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi ha inventato l''iconico abitino nero?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Dov''è stato inventato il Jeans?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Qual è il più famoso stilista italiano noto per i suoi abiti da sposa?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale famosa casa di moda usa la testa di Medusa come logo?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    -- ── Generale / Letteratura (1) ────────────────────────────────────
    (
        'clickfirst',
        'Qual è stato il primo libro stampato?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi ha scritto "Il nome della rosa"?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi ha scritto il famoso romanzo "Dracula"?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale personaggio inventa la scrittrice Mary Shelley?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi ha scritto l''Eneide?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi ha scritto la poesia "M''illumino d''immenso"?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale opera inizia con il verso "La donzelletta vien dalla campagna…"?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Dove si è fermato Cristo secondo Levi?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Come si chiama la strada immaginaria dove viveva Sherlock Holmes?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi diede il nome definitivo alla Divina Commedia?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quanti sono i canti della Divina Commedia?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Chi fu il primo scrittore italiano a ricevere il Premio Nobel per la letteratura?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quanti volumi ci sono nella serie di Harry Potter?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quale celebre personaggio è stato creato dalla scrittrice Agatha Christie, oltre a Poirot?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    -- ── Generale (1) ──────────────────────────────────────────────────
    (
        'clickfirst',
        'Quali sono i nomi dei 7 nani?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    ),
    (
        'clickfirst',
        'Quali sono i 7 peccati capitali?',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        10
    );
